### ISSUE TITLE
Accumulator behavior

### ISSUE THREAD

**Issue by kajmaj** [hhaim/hass#10]
Hello,
I am trying tu use accumulator to count "ON time" of the heater. 
It works, but in the weird way:
If I restart hassio, accumulator starts accumulate, does not matter the state of the switch (relay) in the time of hassio restart. 
It simply counts in both cases ie. relay is ON or OFF after hassio restart.
If it is OFF I have to manually ON and back to OFF again to stop counting.

Switch configuration:
```
switch:
  - platform: mqtt
    name: "heater_b"
    command_topic: "cmnd/bathroom/power"
    state_topic: "stat/bathroom/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
```
Accumulator config:
```
  - platform: accumulator     
    name: bathroom_clock
    entity_id: switch.heater_b
    state_on: 'on'
    state_off: 'off'
```

Is there any way around hot to make it working properly?
